### ISSUE TITLE
Account type based on first letter of random name

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Contracts#5]
**User story**

As a developer
I can determine the type (Person, Org, Gov, Contract etc) using the first letter of the accounts name
so that I can quickly and efficiently find the data about that entity which is in different tables

**Definition of done**

- [x] The first letter of a random account name is fixed based on the account type

Person = p
Organization = o
Goverment = g
Smart contract = s

**Comment by theblockstalk** [comment]
@Rebal67 during this task we should also remove the type struct member variable for the eosio table, as it is redundant. I have created a follow up task for this for the SDK here
https://app.zenhub.com/workspaces/tonomy-id-62a06b705d27820023023630/issues/tonomy-foundation/tonomy-id-sdk/40

**Comment by Rebal67** [comment]
Strict remove from table and creating an account and from unit test
