### ISSUE TITLE
Tonomy network mainnet: research resource model

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Contracts#71]
Acceptance criteria

- [x] Research how the resource model is implemented on antelope change. check differences in the REX, Powerup and staking models and how they were implemented
- [x] Design a resource model and how it could be implanted (with pseudocode) to allow for each account created will have equal access to resources on the network

**Comment by theblockstalk** [comment]
https://docs.eosnetwork.com/docs/latest/core-concepts/resources

Reference: https://github.com/AntelopeIO/reference-contracts/tree/main/contracts
EOS: https://github.com/eosnetworkfoundation/eos-system-contracts/tree/main/contracts/eosio.system
Telos: 
WAX: 

https://eos.io/news/eos-powerup-model-explained/
https://medium.com/eosys/eos-inside-the-ultimate-guide-to-eosrex-b9b6d479a8eb
https://topstaking.com/stake-eos/

**Comment by sadiabbasi** [comment]
https://docs.google.com/document/d/1mO33PVx_SwBX9OqXoVEQij_Tr3ypUBVrYnE8QksP8ZA

**Comment by theblockstalk** [comment]
RAM using Bancor: https://docs.eosnetwork.com/docs/latest/core-concepts/resources/

**Comment by theblockstalk** [comment]
last sprint: 2
next sprint: 3
