### ISSUE TITLE
Vesting contract

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Contracts#85]
Acceptance criteria
- [ ] Tokens purchased during the private or public sale are only a vesting schedule as defined in our token design
- [ ] Such tokens will have a cliff (e.g. 6 months) and Before which all of the purchase tokens are locked. After the cliff date and until the end of the vesting schedule (e.g.24 months) coins are unlocked linearly to List them all at the end of the vesting schedule

Two ways to do this:
- [ ] eosio.token token transfers for From the coinsale.tmy account are under a vesting schedule
- [ ] Creates epic contract which tokens are sent to and assigned to people Which can be withdrawn back to their own account with the vesting logic

**Comment by theblockstalk** [comment]
vesting schedule: https://docs.google.com/spreadsheets/d/1uyvpgXC0th3Z1_bz4m18dJKy2yyVfYFmcaEyS9fveeA/edit#gid=1294999691

**Comment by theblockstalk** [comment]
https://github.com/maltablock/telos-vesting-contract

**Comment by theblockstalk** [comment]
https://github.com/fikkyJ/kowe-contracts

**Comment by theblockstalk** [comment]
https://github.com/StanChe/vesting.token

**Comment by sadiabbasi** [comment]
several different pools some of the different pools having different schedule.
